import { ProfileData } from "@/types/profile";
import { IMAGES } from "./image.index";

export const profiles: ProfileData[] = [

  // ================= RECEIVED =================
  // Pending (6)
  {
    id: "R-P-01",
    profileId: "P-01",
    mainTab: "received",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Ayesha Rahman",
    about: "Software professional.",
    basicInfo: {
      age: 25,
      religion: "Muslim",
      gender: "Female",
    },
    moreInfo: {
      height: "5'2\"",
      weight: "N/A",
      skinTone: "Fair",
      bodyType: "Slim",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Engineer",
      motherStatus: "Alive",
      motherOccupation: "Teacher",
      siblings: "1",
      sisters: "0",
      affluence: "Middle Class",
      livesIn: "Dhaka",
    },
    education: {
      education: "BSc Computer Science",
      institute: "Dhaka University",
      profession: "Software Engineer",
      monthlyIncome: "50000",
      areaField: "Tech",
      company: "Tech Corp",
    },
    address: {
      homeDistrict: "Dhaka",
      city: "Dhaka",
      country: "Bangladesh",
      postalCode: "1207",
      location: "Sector 10",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: true,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Reading, Coding",
    },
  },
  {
    id: "R-P-02",
    profileId: "P-02",
    mainTab: "received",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Nusrat Jahan",
    about: "Entrepreneur.",
    basicInfo: {
      age: 27,
      religion: "Muslim",
      gender: "Female",
    },
    moreInfo: {
      height: "5'4\"",
      weight: "N/A",
      skinTone: "Fair",
      bodyType: "Medium",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Divorced",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Businessman",
      motherStatus: "Alive",
      motherOccupation: "Housewife",
      siblings: "2",
      sisters: "1",
      affluence: "High Class",
      livesIn: "Sylhet",
    },
    education: {
      education: "MBA",
      institute: "Sylhet University",
      profession: "Entrepreneur",
      monthlyIncome: "100000",
      areaField: "Business",
      company: "Nusrat Enterprises",
    },
    address: {
      homeDistrict: "Sylhet",
      city: "Sylhet",
      country: "Bangladesh",
      postalCode: "3100",
      location: "Mirpur",
    },
    lifestyle: {
      smoking: true,
      drinking: true,
      vegetarian: false,
      annoyane: false,
      badMood: false,
      recklessDriving: true,
      hobbies: "Traveling, Shopping",
    },
  },
  {
    id: "R-P-03",
    profileId: "P-03",
    mainTab: "received",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Sadia Islam",
    about: "University student.",
    basicInfo: {
      age: 24,
      religion: "Muslim",
      gender: "Female",
    },
    moreInfo: {
      height: "5'3\"",
      weight: "N/A",
      skinTone: "Medium",
      bodyType: "Petite",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Teacher",
      motherStatus: "Alive",
      motherOccupation: "Doctor",
      siblings: "3",
      sisters: "2",
      affluence: "Middle Class",
      livesIn: "Rajshahi",
    },
    education: {
      education: "BBA",
      institute: "Rajshahi University",
      profession: "Student",
      monthlyIncome: "N/A",
      areaField: "Education",
      company: "N/A",
    },
    address: {
      homeDistrict: "Rajshahi",
      city: "Rajshahi",
      country: "Bangladesh",
      postalCode: "6200",
      location: "Bashundhara",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: true,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Studying, Reading",
    },
  },
  {
    id: "R-P-04",
    profileId: "P-04",
    mainTab: "received",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Rima Khatun",
    about: "Marketing professional.",
    basicInfo: {
      age: 28,
      religion: "Muslim",
      gender: "Female",
    },
    moreInfo: {
      height: "5'5\"",
      weight: "N/A",
      skinTone: "Dark",
      bodyType: "Curvy",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Doctor",
      motherStatus: "Alive",
      motherOccupation: "Housewife",
      siblings: "2",
      sisters: "1",
      affluence: "High Class",
      livesIn: "Chattogram",
    },
    education: {
      education: "Masters in Business",
      institute: "Chattogram University",
      profession: "Marketing Manager",
      monthlyIncome: "80000",
      areaField: "Marketing",
      company: "Marketing Solutions",
    },
    address: {
      homeDistrict: "Chattogram",
      city: "Chattogram",
      country: "Bangladesh",
      postalCode: "4000",
      location: "Hill View",
    },
    lifestyle: {
      smoking: true,
      drinking: true,
      vegetarian: false,
      annoyane: false,
      badMood: false,
      recklessDriving: true,
      hobbies: "Shopping, Traveling",
    },
  },
  {
    id: "R-P-05",
    profileId: "P-05",
    mainTab: "received",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Sharmin Sultana",
    about: "Content writer.",
    basicInfo: {
      age: 30,
      religion: "Muslim",
      gender: "Female",
    },
    moreInfo: {
      height: "5'6\"",
      weight: "N/A",
      skinTone: "Medium",
      bodyType: "Athletic",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Engineer",
      motherStatus: "Alive",
      motherOccupation: "Housewife",
      siblings: "2",
      sisters: "1",
      affluence: "Middle Class",
      livesIn: "Dhaka",
    },
    education: {
      education: "Masters in English Literature",
      institute: "Dhaka University",
      profession: "Content Writer",
      monthlyIncome: "40000",
      areaField: "Writing",
      company: "Content Creators",
    },
    address: {
      homeDistrict: "Dhaka",
      city: "Dhaka",
      country: "Bangladesh",
      postalCode: "1210",
      location: "Banani",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: true,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Writing, Reading",
    },
  },
  {
    id: "R-P-06",
    profileId: "P-06",
    mainTab: "received",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Jannatul Ferdous",
    about: "Marketing executive.",
    basicInfo: {
      age: 27,
      religion: "Muslim",
      gender: "Female",
    },
    moreInfo: {
      height: "5'3\"",
      weight: "N/A",
      skinTone: "Fair",
      bodyType: "Slim",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Doctor",
      motherStatus: "Alive",
      motherOccupation: "Teacher",
      siblings: "1",
      sisters: "0",
      affluence: "Middle Class",
      livesIn: "Mymensingh",
    },
    education: {
      education: "BBA",
      institute: "Mymensingh University",
      profession: "Marketing Executive",
      monthlyIncome: "40000",
      areaField: "Marketing",
      company: "XYZ Marketing",
    },
    address: {
      homeDistrict: "Mymensingh",
      city: "Mymensingh",
      country: "Bangladesh",
      postalCode: "2200",
      location: "Town Hall",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: true,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Traveling, Socializing",
    },
  },

  // ================= RECEIVED =================
  // Accepted (6)
  {
    id: "R-A-01",
    profileId: "P-01",
    mainTab: "received",
    status: "accepted",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Maliha Hasan",
    about: "School teacher.",
    basicInfo: {
      age: 31,
      religion: "Muslim",
      gender: "Female",
    },
    moreInfo: {
      height: "5'6\"",
      weight: "N/A",
      skinTone: "Fair",
      bodyType: "Slim",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Widowed",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Retired",
      motherStatus: "Alive",
      motherOccupation: "Housewife",
      siblings: "3",
      sisters: "2",
      affluence: "Middle Class",
      livesIn: "Khulna",
    },
    education: {
      education: "Bachelors in Education",
      institute: "Khulna University",
      profession: "Primary School Teacher",
      monthlyIncome: "40000",
      areaField: "Education",
      company: "Khulna Public School",
    },
    address: {
      homeDistrict: "Khulna",
      city: "Khulna",
      country: "Bangladesh",
      postalCode: "9000",
      location: "Gulshan",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: true,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Reading, Teaching",
    },
  },
  // ================= SENT =================
  // Pending (6)
  {
    id: "S-P-01",
    profileId: "P-01",
    mainTab: "sent",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "User 1",
    about: "Sent pending 1",
    basicInfo: {
      age: 26,
      religion: "Muslim",
      gender: "Male",
    },
    moreInfo: {
      height: "5'4\"",
      weight: "N/A",
      skinTone: "Fair",
      bodyType: "Slim",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Engineer",
      motherStatus: "Alive",
      motherOccupation: "Teacher",
      siblings: "2",
      sisters: "1",
      affluence: "Middle Class",
      livesIn: "Dhaka",
    },
    education: {
      education: "BSc Computer Science",
      institute: "Dhaka University",
      profession: "Software Engineer",
      monthlyIncome: "60000",
      areaField: "Tech",
      company: "Tech Corp",
    },
    address: {
      homeDistrict: "Dhaka",
      city: "Dhaka",
      country: "Bangladesh",
      postalCode: "1207",
      location: "Sector 10",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: true,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Coding, Reading",
    },
  },
  {
    id: "S-P-02",
    profileId: "P-02",
    mainTab: "sent",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "User 2",
    about: "Sent pending 2",
    basicInfo: {
      age: 28,
      religion: "Muslim",
      gender: "Male",
    },
    moreInfo: {
      height: "5'5\"",
      weight: "N/A",
      skinTone: "Fair",
      bodyType: "Medium",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Businessman",
      motherStatus: "Alive",
      motherOccupation: "Housewife",
      siblings: "3",
      sisters: "1",
      affluence: "High Class",
      livesIn: "Chattogram",
    },
    education: {
      education: "BBA",
      institute: "Chattogram University",
      profession: "Business Analyst",
      monthlyIncome: "70000",
      areaField: "Business",
      company: "Business Solutions",
    },
    address: {
      homeDistrict: "Chattogram",
      city: "Chattogram",
      country: "Bangladesh",
      postalCode: "4000",
      location: "KDA",
    },
    lifestyle: {
      smoking: true,
      drinking: true,
      vegetarian: false,
      annoyane: false,
      badMood: false,
      recklessDriving: true,
      hobbies: "Shopping, Traveling",
    },
  },
  {
    id: "S-P-03",
    profileId: "P-03",
    mainTab: "sent",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "User 3",
    about: "Sent pending 3",
    basicInfo: {
      age: 24,
      religion: "Muslim",
      gender: "Male",
    },
    moreInfo: {
      height: "5'2\"",
      weight: "N/A",
      skinTone: "Medium",
      bodyType: "Slim",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Retired",
      motherStatus: "Alive",
      motherOccupation: "Teacher",
      siblings: "1",
      sisters: "0",
      affluence: "Middle Class",
      livesIn: "Rajshahi",
    },
    education: {
      education: "BSc Mechanical Engineering",
      institute: "Rajshahi University",
      profession: "Engineer",
      monthlyIncome: "50000",
      areaField: "Engineering",
      company: "Engineering Corp",
    },
    address: {
      homeDistrict: "Rajshahi",
      city: "Rajshahi",
      country: "Bangladesh",
      postalCode: "6200",
      location: "Puthia",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: true,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Reading, Cricket",
    },
  },
  {
    id: "S-P-04",
    profileId: "P-04",
    mainTab: "sent",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "User 4",
    about: "Sent pending 4",
    basicInfo: {
      age: 29,
      religion: "Muslim",
      gender: "Male",
    },
    moreInfo: {
      height: "5'6\"",
      weight: "N/A",
      skinTone: "Fair",
      bodyType: "Athletic",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Doctor",
      motherStatus: "Alive",
      motherOccupation: "Housewife",
      siblings: "3",
      sisters: "1",
      affluence: "High Class",
      livesIn: "Khulna",
    },
    education: {
      education: "MBA",
      institute: "Khulna University",
      profession: "Business Manager",
      monthlyIncome: "90000",
      areaField: "Management",
      company: "Khulna Enterprises",
    },
    address: {
      homeDistrict: "Khulna",
      city: "Khulna",
      country: "Bangladesh",
      postalCode: "9000",
      location: "Gulshan",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: false,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Football, Business",
    },
  },
  {
    id: "S-P-05",
    profileId: "P-05",
    mainTab: "sent",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "User 5",
    about: "Sent pending 5",
    basicInfo: {
      age: 30,
      religion: "Muslim",
      gender: "Male",
    },
    moreInfo: {
      height: "5'7\"",
      weight: "N/A",
      skinTone: "Medium",
      bodyType: "Medium",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Teacher",
      motherStatus: "Alive",
      motherOccupation: "Nurse",
      siblings: "2",
      sisters: "0",
      affluence: "Middle Class",
      livesIn: "Mymensingh",
    },
    education: {
      education: "BBA",
      institute: "Mymensingh University",
      profession: "Content Writer",
      monthlyIncome: "30000",
      areaField: "Content Creation",
      company: "Mymensingh Writers",
    },
    address: {
      homeDistrict: "Mymensingh",
      city: "Mymensingh",
      country: "Bangladesh",
      postalCode: "2200",
      location: "Main Road",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: true,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Writing, Yoga",
    },
  },
  {
    id: "S-P-06",
    profileId: "P-06",
    mainTab: "sent",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "User 6",
    about: "Sent pending 6",
    basicInfo: {
      age: 31,
      religion: "Muslim",
      gender: "Male",
    },
    moreInfo: {
      height: "5'8\"",
      weight: "N/A",
      skinTone: "Dark",
      bodyType: "Athletic",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Lawyer",
      motherStatus: "Alive",
      motherOccupation: "Doctor",
      siblings: "2",
      sisters: "0",
      affluence: "High Class",
      livesIn: "Barishal",
    },
    education: {
      education: "Masters in Law",
      institute: "Barishal University",
      profession: "Lawyer",
      monthlyIncome: "100000",
      areaField: "Law",
      company: "Barishal Law Firm",
    },
    address: {
      homeDistrict: "Barishal",
      city: "Barishal",
      country: "Bangladesh",
      postalCode: "8000",
      location: "Sadarghat",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: false,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Reading, Tennis",
    },
  },

  // ================= SENT =================
  // Accepted (6)
  {
    id: "S-A-01",
    profileId: "P-01",
    mainTab: "sent",
    status: "accepted",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "User 7",
    about: "Sent accepted 1",
    basicInfo: {
      age: 32,
      religion: "Muslim",
      gender: "Male",
    },
    moreInfo: {
      height: "5'9\"",
      weight: "N/A",
      skinTone: "Fair",
      bodyType: "Muscular",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Doctor",
      motherStatus: "Alive",
      motherOccupation: "Housewife",
      siblings: "2",
      sisters: "1",
      affluence: "High Class",
      livesIn: "Sylhet",
    },
    education: {
      education: "BSc Business Administration",
      institute: "Sylhet University",
      profession: "Businessman",
      monthlyIncome: "120000",
      areaField: "Business",
      company: "Sylhet Enterprise",
    },
    address: {
      homeDistrict: "Sylhet",
      city: "Sylhet",
      country: "Bangladesh",
      postalCode: "3100",
      location: "Noyashor",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: true,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Traveling, Cooking",
    },
  },
  // ================= BLOCKED =================
  // Pending (6)
  {
    id: "B-P-01",
    profileId: "P-01",
    mainTab: "blocked",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Blocked 1",
    about: "Blocked pending 1",
    basicInfo: {
      age: 29,
      religion: "Muslim",
      gender: "Female",
    },
    moreInfo: {
      height: "5'4\"",
      weight: "N/A",
      skinTone: "Fair",
      bodyType: "Slim",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Engineer",
      motherStatus: "Alive",
      motherOccupation: "Teacher",
      siblings: "2",
      sisters: "1",
      affluence: "Middle Class",
      livesIn: "Dhaka",
    },
    education: {
      education: "BSc Computer Science",
      institute: "Dhaka University",
      profession: "Software Engineer",
      monthlyIncome: "50000",
      areaField: "Tech",
      company: "Tech Corp",
    },
    address: {
      homeDistrict: "Dhaka",
      city: "Dhaka",
      country: "Bangladesh",
      postalCode: "1207",
      location: "Mirpur",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: true,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Reading, Coding",
    },
  },
  {
    id: "B-P-02",
    profileId: "P-02",
    mainTab: "blocked",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Blocked 2",
    about: "Blocked pending 2",
    basicInfo: {
      age: 27,
      religion: "Muslim",
      gender: "Male",
    },
    moreInfo: {
      height: "5'6\"",
      weight: "N/A",
      skinTone: "Medium",
      bodyType: "Muscular",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Businessman",
      motherStatus: "Alive",
      motherOccupation: "Housewife",
      siblings: "3",
      sisters: "2",
      affluence: "High Class",
      livesIn: "Sylhet",
    },
    education: {
      education: "MBA",
      institute: "Sylhet University",
      profession: "Entrepreneur",
      monthlyIncome: "100000",
      areaField: "Business",
      company: "Sylhet Enterprises",
    },
    address: {
      homeDistrict: "Sylhet",
      city: "Sylhet",
      country: "Bangladesh",
      postalCode: "3100",
      location: "Noyashor",
    },
    lifestyle: {
      smoking: true,
      drinking: true,
      vegetarian: false,
      annoyane: false,
      badMood: false,
      recklessDriving: true,
      hobbies: "Traveling, Shopping",
    },
  },
  {
    id: "B-P-03",
    profileId: "P-03",
    mainTab: "blocked",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Blocked 3",
    about: "Blocked pending 3",
    basicInfo: {
      age: 31,
      religion: "Muslim",
      gender: "Female",
    },
    moreInfo: {
      height: "5'7\"",
      weight: "N/A",
      skinTone: "Fair",
      bodyType: "Curvy",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Divorced",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Lawyer",
      motherStatus: "Alive",
      motherOccupation: "Nurse",
      siblings: "1",
      sisters: "0",
      affluence: "Middle Class",
      livesIn: "Rajshahi",
    },
    education: {
      education: "LLB",
      institute: "Rajshahi University",
      profession: "Lawyer",
      monthlyIncome: "70000",
      areaField: "Law",
      company: "Rajshahi Law Firm",
    },
    address: {
      homeDistrict: "Rajshahi",
      city: "Rajshahi",
      country: "Bangladesh",
      postalCode: "6200",
      location: "Bashundhara",
    },
    lifestyle: {
      smoking: false,
      drinking: true,
      vegetarian: false,
      annoyane: false,
      badMood: false,
      recklessDriving: true,
      hobbies: "Reading, Sports",
    },
  },
  {
    id: "B-P-04",
    profileId: "P-04",
    mainTab: "blocked",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Blocked 4",
    about: "Blocked pending 4",
    basicInfo: {
      age: 25,
      religion: "Muslim",
      gender: "Male",
    },
    moreInfo: {
      height: "5'8\"",
      weight: "N/A",
      skinTone: "Dark",
      bodyType: "Athletic",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Teacher",
      motherStatus: "Alive",
      motherOccupation: "Doctor",
      siblings: "2",
      sisters: "1",
      affluence: "High Class",
      livesIn: "Barishal",
    },
    education: {
      education: "Masters in Computer Science",
      institute: "Barishal University",
      profession: "Software Developer",
      monthlyIncome: "80000",
      areaField: "Software Development",
      company: "Tech Solutions",
    },
    address: {
      homeDistrict: "Barishal",
      city: "Barishal",
      country: "Bangladesh",
      postalCode: "8000",
      location: "Nazarabad",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: true,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Gaming, Hiking",
    },
  },
  {
    id: "B-P-05",
    profileId: "P-05",
    mainTab: "blocked",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Blocked 5",
    about: "Blocked pending 5",
    basicInfo: {
      age: 30,
      religion: "Muslim",
      gender: "Female",
    },
    moreInfo: {
      height: "5'5\"",
      weight: "N/A",
      skinTone: "Fair",
      bodyType: "Medium",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Doctor",
      motherStatus: "Alive",
      motherOccupation: "Housewife",
      siblings: "2",
      sisters: "1",
      affluence: "Middle Class",
      livesIn: "Khulna",
    },
    education: {
      education: "MBA",
      institute: "Khulna University",
      profession: "HR Manager",
      monthlyIncome: "60000",
      areaField: "Human Resources",
      company: "HR Solutions",
    },
    address: {
      homeDistrict: "Khulna",
      city: "Khulna",
      country: "Bangladesh",
      postalCode: "9000",
      location: "Shahbagh",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: true,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Traveling, Yoga",
    },
  },
  {
    id: "B-P-06",
    profileId: "P-06",
    mainTab: "blocked",
    status: "pending",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Blocked 6",
    about: "Blocked pending 6",
    basicInfo: {
      age: 28,
      religion: "Muslim",
      gender: "Male",
    },
    moreInfo: {
      height: "5'9\"",
      weight: "N/A",
      skinTone: "Medium",
      bodyType: "Athletic",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Engineer",
      motherStatus: "Alive",
      motherOccupation: "Housewife",
      siblings: "1",
      sisters: "0",
      affluence: "Middle Class",
      livesIn: "Rangpur",
    },
    education: {
      education: "BSc Electrical Engineering",
      institute: "Rangpur University",
      profession: "Electrical Engineer",
      monthlyIncome: "70000",
      areaField: "Engineering",
      company: "Electrical Solutions",
    },
    address: {
      homeDistrict: "Rangpur",
      city: "Rangpur",
      country: "Bangladesh",
      postalCode: "5400",
      location: "Moylapota",
    },
    lifestyle: {
      smoking: false,
      drinking: true,
      vegetarian: false,
      annoyane: false,
      badMood: false,
      recklessDriving: true,
      hobbies: "Sports, Fitness",
    },
  },

  // ================= BLOCKED =================
  // Accepted (6)
  {
    id: "B-A-01",
    profileId: "P-01",
    mainTab: "blocked",
    status: "accepted",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Blocked 7",
    about: "Blocked accepted 1",
    basicInfo: {
      age: 32,
      religion: "Muslim",
      gender: "Male",
    },
    moreInfo: {
      height: "5'8\"",
      weight: "N/A",
      skinTone: "Fair",
      bodyType: "Slim",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Engineer",
      motherStatus: "Alive",
      motherOccupation: "Teacher",
      siblings: "2",
      sisters: "1",
      affluence: "Middle Class",
      livesIn: "Mymensingh",
    },
    education: {
      education: "BSc Business Administration",
      institute: "Mymensingh University",
      profession: "Business Manager",
      monthlyIncome: "100000",
      areaField: "Business",
      company: "Mymensingh Enterprise",
    },
    address: {
      homeDistrict: "Mymensingh",
      city: "Mymensingh",
      country: "Bangladesh",
      postalCode: "2200",
      location: "Main Road",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: true,
      annoyane: false,
      badMood: false,
      recklessDriving: false,
      hobbies: "Reading, Traveling",
    },
  },
];
