import { ProfileData } from "@/types/profile";
import { IMAGES } from "./image.index";

export const profiles: ProfileData[] = [
  /* ================= RECEIVED - PENDING (6) ================= */
  {
    id: "R-P-01",
    profileId: "RP-01",
    idNo: "ID-1001",
    mainTab: "received",
    status: "pending",
    coverImage: IMAGES.profile1.src,
    profileImage: IMAGES.profile1.src,
    images: [IMAGES.profile1.src],
    name: "Received Pending 1",
    about: "Pending received profile",
    email: "rp1@gmail.com",
    mobileNumber: "01710000001",
    basicInfo: { age: 24, religion: "Muslim", gender: "Female" },
    moreInfo: {
      height: "5'2\"",
      weight: "50kg",
      skinTone: "Fair",
      bodyType: "Slim",
      bloodGroup: "O+",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Engineer",
      motherStatus: "Alive",
      motherOccupation: "Teacher",
      siblings: { brothers: 1, sisters: 1 },
      affluence: "Middle",
      livesIn: "Dhaka",
    },
    education: {
      education: "BSc",
      institute: "DU",
      profession: "Engineer",
      monthlyIncome: "50000",
      areaField: "IT",
      company: "Tech Ltd",
    },
    address: {
      homeDistrict: "Dhaka",
      city: "Dhaka",
      country: "Bangladesh",
      postalCode: "1207",
      location: "Mirpur",
      presentAddress: "Dhaka",
      permanentAddress: "Dhaka",
      citizen: "Bangladeshi",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: false,
      badMood: false,
      recklessDriving: false,
      arrogant: false,
      hobbies: "Reading",
      otherHobbies: "Travel",
    },
  },
  {
    id: "R-P-02",
    profileId: "RP-02",
    idNo: "ID-1002",
    mainTab: "received",
    status: "pending",
    coverImage: IMAGES.profile1.src,
    profileImage: IMAGES.profile1.src,
    images: [IMAGES.profile1.src],
    name: "Received Pending 2",
    about: "Pending received profile",
    email: "rp2@gmail.com",
    mobileNumber: "01710000002",
    basicInfo: { age: 25, religion: "Muslim", gender: "Female" },
    moreInfo: {
      height: "5'3\"",
      weight: "52kg",
      skinTone: "Light",
      bodyType: "Average",
      bloodGroup: "A+",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Business",
      motherStatus: "Alive",
      motherOccupation: "Housewife",
      siblings: { brothers: 0, sisters: 1 },
      affluence: "Middle",
      livesIn: "Dhaka",
    },
    education: {
      education: "Honours",
      institute: "NU",
      profession: "Student",
      monthlyIncome: "0",
      areaField: "Arts",
      company: "N/A",
    },
    address: {
      homeDistrict: "Dhaka",
      city: "Dhaka",
      country: "Bangladesh",
      postalCode: "1206",
      location: "Uttara",
      presentAddress: "Dhaka",
      permanentAddress: "Dhaka",
      citizen: "Bangladeshi",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: true,
      badMood: false,
      recklessDriving: false,
      arrogant: false,
      hobbies: "Cooking",
      otherHobbies: "Music",
    },
  },
  {
    id: "R-A-01",
    profileId: "RA-01",
    idNo: "ID-2001",
    mainTab: "received",
    status: "accepted",
    coverImage: IMAGES.profile2.src,
    profileImage: IMAGES.profile2.src,
    images: [IMAGES.profile2.src],
    name: "Received Accepted 1",
    about: "Accepted received profile",
    email: "ra1@gmail.com",
    mobileNumber: "01810000001",
    basicInfo: { age: 26, religion: "Muslim", gender: "Female" },
    moreInfo: {
      height: "5'4\"",
      weight: "55kg",
      skinTone: "Fair",
      bodyType: "Fit",
      bloodGroup: "B+",
      community: "Muslim",
      profileFor: "Marriage",
      maritalStatus: "Unmarried",
    },
    family: {
      fatherStatus: "Alive",
      fatherOccupation: "Doctor",
      motherStatus: "Alive",
      motherOccupation: "Teacher",
      siblings: { brothers: 1, sisters: 0 },
      affluence: "Upper Middle",
      livesIn: "Sylhet",
    },
    education: {
      education: "Masters",
      institute: "DU",
      profession: "Lecturer",
      monthlyIncome: "60000",
      areaField: "Education",
      company: "College",
    },
    address: {
      homeDistrict: "Sylhet",
      city: "Sylhet",
      country: "Bangladesh",
      postalCode: "3100",
      location: "Zindabazar",
      presentAddress: "Sylhet",
      permanentAddress: "Sylhet",
      citizen: "Bangladeshi",
    },
    lifestyle: {
      smoking: false,
      drinking: false,
      vegetarian: false,
      badMood: false,
      recklessDriving: false,
      arrogant: false,
      hobbies: "Teaching",
      otherHobbies: "Gardening",
    },
  },
];

