import { ProfileData } from "@/types/profile";
import { IMAGES } from "./image.index";

export const profiles: ProfileData[] = [
  // ================= RECEIVED =================
  // Pending (3)
  {
    id: "R-P-01",
    name: "Ayesha Rahman",
    age: 25,
    height: "5'2\"",
    bloodGroup: "B+",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Software professional.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "pending",
  },
  {
    id: "R-P-02",
    name: "Nusrat Jahan",
    age: 27,
    height: "5'4\"",
    bloodGroup: "O+",
    city: "Sylhet",
    religion: "Muslim",
    maritalStatus: "Divorced",
    about: "Entrepreneur.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "pending",
  },
  {
    id: "R-P-03",
    name: "Sadia Islam",
    age: 24,
    height: "5'3\"",
    bloodGroup: "A+",
    city: "Rajshahi",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "University student.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "pending",
  },
  {
    id: "R-P-04",
    name: "Sadia Islam",
    age: 24,
    height: "5'3\"",
    bloodGroup: "A+",
    city: "Rajshahi",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "University student.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "pending",
  },
  {
    id: "R-P-05",
    name: "Sadia Islam",
    age: 24,
    height: "5'3\"",
    bloodGroup: "A+",
    city: "Rajshahi",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "University student.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "pending",
  },
  {
    id: "R-P-06",
    name: "Sadia Islam",
    age: 24,
    height: "5'3\"",
    bloodGroup: "A+",
    city: "Rajshahi",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "University student.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "pending",
  },

  // Accepted (3)
  {
    id: "R-A-01",
    name: "Maliha Hasan",
    age: 31,
    height: "5'6\"",
    bloodGroup: "O-",
    city: "Khulna",
    religion: "Muslim",
    maritalStatus: "Widowed",
    about: "School teacher.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "accepted",
  },
  {
    id: "R-A-02",
    name: "Tania Ahmed",
    age: 28,
    height: "5'5\"",
    bloodGroup: "AB+",
    city: "Rangpur",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "HR professional.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "accepted",
  },
  {
    id: "R-A-03",
    name: "Farzana Akter",
    age: 26,
    height: "5'4\"",
    bloodGroup: "B-",
    city: "Comilla",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Banker.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "accepted",
  },
  {
    id: "R-A-04",
    name: "Farzana Akter",
    age: 26,
    height: "5'4\"",
    bloodGroup: "B-",
    city: "Comilla",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Banker.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "accepted",
  },
  {
    id: "R-A-05",
    name: "Farzana Akter",
    age: 26,
    height: "5'4\"",
    bloodGroup: "B-",
    city: "Comilla",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Banker.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "accepted",
  },
  {
    id: "R-A-06",
    name: "Farzana Akter",
    age: 26,
    height: "5'4\"",
    bloodGroup: "B-",
    city: "Comilla",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Banker.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "accepted",
  },

  // Rejected (3)
  {
    id: "R-R-01",
    name: "Rima Khatun",
    age: 29,
    height: "5'5\"",
    bloodGroup: "O+",
    city: "Barishal",
    religion: "Muslim",
    maritalStatus: "Divorced",
    about: "NGO worker.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "rejected",
  },
  {
    id: "R-R-02",
    name: "Sharmin Sultana",
    age: 30,
    height: "5'6\"",
    bloodGroup: "A-",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Content writer.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "rejected",
  },
  {
    id: "R-R-03",
    name: "Jannatul Ferdous",
    age: 27,
    height: "5'3\"",
    bloodGroup: "B+",
    city: "Mymensingh",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Marketing executive.",
    image: IMAGES.profile2.src,
    mainTab: "received",
    status: "rejected",
  },

  // ================= SENT =================
  // Pending (3)
  {
    id: "S-P-01",
    name: "User 1",
    age: 26,
    height: "5'4\"",
    bloodGroup: "O+",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Sent pending 1",
    image: IMAGES.profile2.src,
    mainTab: "sent",
    status: "pending",
  },
  {
    id: "S-P-02",
    name: "User 2",
    age: 28,
    height: "5'5\"",
    bloodGroup: "A+",
    city: "Chattogram",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Sent pending 2",
    image: IMAGES.profile2.src,
    mainTab: "sent",
    status: "pending",
  },
  {
    id: "S-P-03",
    name: "User 3",
    age: 24,
    height: "5'2\"",
    bloodGroup: "B+",
    city: "Sylhet",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Sent pending 3",
    image: IMAGES.profile2.src,
    mainTab: "sent",
    status: "pending",
  },

  // Accepted (3)
  {
    id: "S-A-01",
    name: "User 4",
    age: 29,
    height: "5'6\"",
    bloodGroup: "AB+",
    city: "Khulna",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Sent accepted 1",
    image: IMAGES.profile2.src,
    mainTab: "sent",
    status: "accepted",
  },
  {
    id: "S-A-02",
    name: "User 5",
    age: 27,
    height: "5'4\"",
    bloodGroup: "O-",
    city: "Rajshahi",
    religion: "Muslim",
    maritalStatus: "Divorced",
    about: "Sent accepted 2",
    image: IMAGES.profile2.src,
    mainTab: "sent",
    status: "accepted",
  },
  {
    id: "S-A-03",
    name: "User 6",
    age: 31,
    height: "5'7\"",
    bloodGroup: "A+",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Widowed",
    about: "Sent accepted 3",
    image: IMAGES.profile2.src,
    mainTab: "sent",
    status: "accepted",
  },

  // Rejected (3)
  {
    id: "S-R-01",
    name: "User 7",
    age: 26,
    height: "5'3\"",
    bloodGroup: "B+",
    city: "Barishal",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Sent rejected 1",
    image: IMAGES.profile2.src,
    mainTab: "sent",
    status: "rejected",
  },
  {
    id: "S-R-02",
    name: "User 8",
    age: 28,
    height: "5'5\"",
    bloodGroup: "O+",
    city: "Rangpur",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Sent rejected 2",
    image: IMAGES.profile2.src,
    mainTab: "sent",
    status: "rejected",
  },
  {
    id: "S-R-03",
    name: "User 9",
    age: 30,
    height: "5'6\"",
    bloodGroup: "A-",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Divorced",
    about: "Sent rejected 3",
    image: IMAGES.profile2.src,
    mainTab: "sent",
    status: "rejected",
  },

  // ================= BLOCKED =================
  // Pending / Accepted / Rejected (same pattern)
  {
    id: "B-P-01",
    name: "Blocked 1",
    age: 29,
    height: "5'4\"",
    bloodGroup: "O+",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Blocked pending",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "pending",
  },
  {
    id: "B-P-02",
    name: "Blocked 2",
    age: 27,
    height: "5'3\"",
    bloodGroup: "A+",
    city: "Khulna",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Blocked pending",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "pending",
  },
  {
    id: "B-P-03",
    name: "Blocked 3",
    age: 31,
    height: "5'6\"",
    bloodGroup: "B+",
    city: "Sylhet",
    religion: "Muslim",
    maritalStatus: "Divorced",
    about: "Blocked pending",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "pending",
  },

  {
    id: "B-A-01",
    name: "Blocked 4",
    age: 28,
    height: "5'5\"",
    bloodGroup: "AB+",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Blocked accepted",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "accepted",
  },
  {
    id: "B-A-02",
    name: "Blocked 5",
    age: 26,
    height: "5'4\"",
    bloodGroup: "O-",
    city: "Rajshahi",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Blocked accepted",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "accepted",
  },
  {
    id: "B-A-03",
    name: "Blocked 6",
    age: 30,
    height: "5'6\"",
    bloodGroup: "A+",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Widowed",
    about: "Blocked accepted",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "accepted",
  },
  {
    id: "B-A-04",
    name: "Blocked 6",
    age: 30,
    height: "5'6\"",
    bloodGroup: "A+",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Widowed",
    about: "Blocked accepted",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "accepted",
  },
  {
    id: "B-A-05",
    name: "Blocked 6",
    age: 30,
    height: "5'6\"",
    bloodGroup: "A+",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Widowed",
    about: "Blocked accepted",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "accepted",
  },
  {
    id: "B-A-06",
    name: "Blocked 6",
    age: 30,
    height: "5'6\"",
    bloodGroup: "A+",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Widowed",
    about: "Blocked accepted",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "accepted",
  },

  {
    id: "B-R-01",
    name: "Blocked 7",
    age: 25,
    height: "5'2\"",
    bloodGroup: "B+",
    city: "Barishal",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Blocked rejected",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "rejected",
  },
  {
    id: "B-R-02",
    name: "Blocked 8",
    age: 29,
    height: "5'5\"",
    bloodGroup: "O+",
    city: "Rangpur",
    religion: "Muslim",
    maritalStatus: "Divorced",
    about: "Blocked rejected",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "rejected",
  },
  {
    id: "B-R-03",
    name: "Blocked 9",
    age: 31,
    height: "5'7\"",
    bloodGroup: "A-",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Blocked rejected",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "rejected",
  },
  {
    id: "B-R-04",
    name: "Blocked 9",
    age: 31,
    height: "5'7\"",
    bloodGroup: "A-",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Blocked rejected",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "rejected",
  },
  {
    id: "B-R-05",
    name: "Blocked 9",
    age: 31,
    height: "5'7\"",
    bloodGroup: "A-",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Blocked rejected",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "rejected",
  },
  {
    id: "B-R-06",
    name: "Blocked 9",
    age: 31,
    height: "5'7\"",
    bloodGroup: "A-",
    city: "Dhaka",
    religion: "Muslim",
    maritalStatus: "Unmarried",
    about: "Blocked rejected",
    image: IMAGES.profile2.src,
    mainTab: "blocked",
    status: "rejected",
  },
];
